Laptrinhweb/Controllers/ABCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laptrinhweb.Models;
using PagedList;
using PagedList.Mvc;

namespace Laptrinhweb.Controllers
{
    public class ABCController : Controller
    {
        dbABCDataContext data = new dbABCDataContext();
     
        public ActionResult Index()
        {
         
            return View();
        }

        public ActionResult Product()
        {
            var product = from pro in data.Products select pro;
            return PartialView(product);
        }
        public ActionResult Details(int id)
        {
            var pro = from s in data.Products
                       where s.idpro == id
                       select s;
            return View(pro.Single());
        }
        public ActionResult All()
        {
            var cate = from cd in data.Categories select cd;
            return View(cate);
        }
        public ActionResult ProductAll(int id , int ? page)
        {
            int pageSize = 5;
            int pageNum = (page ?? 1);
            var proall = from s in data.Products where s.idcate == id select s;
          
            return View(proall);
        }
        public ActionResult login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(FormCollection collection)
        {
            // Gán các giá trị người dùng nhập liệu cho các biến 
            var tendn = collection["username"];
            var matkhau = collection["password"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "You must enter login name";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "You must enter login password";
            }
            else
            {
                //Gán giá trị cho đối tượng được tạo mới (kh)
                Man m = data.Mans.SingleOrDefault(n => n.username == tendn && n.password == matkhau);
                if (m != null)
                {
                    // ViewBag.Thongbao = "Chúc mừng đăng nhập thành công";
                    Session["Username"] = m;
                    return RedirectToAction("Index", "ABC");
                }
                else
                    ViewBag.Thongbao = "Username or password is in correct";
            }
            return View();
        }
    }
}

Laptrinhweb/Controllers/ManController.cs
using Laptrinhweb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laptrinhweb.Controllers
{
    public class ManController : Controller
    {
        dbABCDataContext db = new dbABCDataContext();
      
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult signin()
        {
            return View();
        }

        
        [HttpPost]
        public ActionResult signin(FormCollection collection, Man kh)
        {
           
            var hoten = collection["HotenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            var matkhaunhaplai = collection["Matkhaunhaplai"];
            var diachi = collection["Diachi"];
            var email = collection["Email"];
            var dienthoai = collection["Dienthoai"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["Ngaysinh"]);
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Customer name cannot be left blank ";
            }
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "Username must be entered ";
            }
            if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Password must be entered ";
            }
            if (String.IsNullOrEmpty(matkhaunhaplai))
            {
                ViewData["Loi4"] = "Password must be re-entered ";
            }
            if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi5"] = "Email is not vacant ";
            }

            if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi6"] = "Must enter phone ";
            }
            else
            {
               

                kh.name = hoten;
                kh.username = tendn;
                kh.password = matkhau;
                kh.email = email;
                kh.address = diachi;
                kh.phone = dienthoai;
                kh.birth = DateTime.Parse(ngaysinh);
                db.Mans.InsertOnSubmit(kh);
                db.SubmitChanges();
              
            }
            return this.signin();
        }
       
        public ActionResult login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult login(FormCollection collection)
        {
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            if(String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Username must be entered ";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Password must be entered";
            }
            else
            {
                Man m = db.Mans.SingleOrDefault(n => n.username == tendn && n.password == matkhau);
                if(m != null)
                {
                    ViewBag.Thongbao = "Congratulations on successful login ";
                    Session["username"] = m;
                    return RedirectToAction("Index", "ABC");
                }
                else
                {
                    ViewBag.Thongbao = "Username or password is incorrect ";
                }
            }

            return View();
        }
    }
}

Laptrinhweb/Views/ABC/All.cshtml
@model IEnumerable<Laptrinhweb.Models.Category>
@{
    ViewBag.Title = "All";
    Layout = "~/Views/Shared/_LayoutABC1.cshtml";
}
<h4><br /><br /><br /><br /></h4>
<div class="example">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <ul class="list-inline">
                    <a href="@Url.Action("ProductAll", "ABC", new { id = item.idcate})" class="list-group list-group-horizontal">
                    <li class="list-group-item list-group-item-action">@item.name </li>
                    </a>
                </ul>
            }
        </div>
        <div>
            <h2><br /><br />Price List</h2>
            <img src="~/Images/banggia.png" width="900" height="1000"/>
        </div>
    </div>
    
</div>

    <style type="text/css">
        .example {
            margin: 20px;
            font-family: 'Segoe Script';
            font-size: 40px;
        }
    </style>

Laptrinhweb/Views/ABC/Details.cshtml
<style type="text/css">
    #Datmua a {
        clear: both;
        background-color: antiquewhite;
        color: white;
        width: 120px;
        height: 35px;
        display: block;
        float: right;
        text-align: center;
        padding-top: 10px;
        text-decoration: none;
        font-weight: bold;
    }

        #Datmua a:hover {
            background-color: gray;
            color: black;
        }
</style>
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutABC1.cshtml";
}

<h2>Details</h2>


<h3><br /><br />Product Details</h3>
<div>
    <div style="width:40%; float:left; border-left: dotted 1px; border-color:azure">
        <img src="~/Images/@Model.image" width="300" height="150" />
    </div>
    <div style="width:50%; float:left; padding:10px">
        <h4 style="font-weight:bold; color:black ; font-size:20px">Name: @Model.namepro </h4>
        <p style="text-align:justify"><Span style="font-weight:bold">Description:</Span>@Model.description </p>
        <p style="font-weight:bold">Price: <span style="color:red; font-size:16pt "> @Model.price VNĐ</span></p>
    </div>
    <div>
       
        <div id="Datmua">
            <a href="@Url.Action("AddCart", "Cart", new { @iidpro = @Model.idpro ,@strURL=Request.Url.ToString()})" style="color:black">Order</a>
            <a href="@Url.Action("All", "ABC")" style="color:black">Back</a>
        </div>

    </div>
</div>

Laptrinhweb/Views/ABC/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutABC.cshtml";
}

<h2>Index</h2>

Laptrinhweb/Views/ABC/Product.cshtml
@model IEnumerable<Laptrinhweb.Models.Product>
@{
    ViewBag.Title = "Product";
    Layout = "~/Views/Shared/_LayoutABC1.cshtml";
}

<h2>Product</h2>
<div class="row">
    @foreach (var pro in Model)
    {
    <a href="@Url.Action("Details", "ABC", new { id = pro.idpro})">
        <img alt="@pro.namepro" src="~/Images/@pro.image" width="200" />
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <div class="caption">
                    <h4 style="text-align:center">@pro.namepro</h4>
                    <br />
                    <h4 class="pull-left">@pro.price</h4>
                    <br />
                </div>
                <div class="ratings">
                    <p class="pull-right">1103 reviews</p>
                    <p>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                    </p>
                </div>
            </div>
        </div>
    </a>
    }
</div>

Laptrinhweb/Views/ABC/ProductAll.cshtml
@model IEnumerable<Laptrinhweb.Models.Product>
    @using Laptrinhweb.Models;


@{
    ViewBag.Title = "ProductAll";
    Layout = "~/Views/Shared/_LayoutABC1.cshtml";
}
<br />
<br />
<br />
<h2>Product</h2>
<div class="row">

    @foreach (var item in Model)
    {

        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details", "ABC", new { id = item.idpro})">
                    <img alt="@item.namepro" src="~/Images/@item.image" />
                    <div class="caption">
                        <h4 style="text-align:center"> @item.namepro  </h4>
                        <h4 class="pull-right">@item.price VNĐ</h4>
                    </div>
                    <div class="ratings">
                        <p class="pull-left">135 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
                </a>
            </div>
        </div>
    }
</div>

<div >
    <h2><a href="@Url.Action("All", "ABC")" style="color:black">Back</a></h2>
</div>

Laptrinhweb/Views/ABC/login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>login</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap Login Form Template</title>

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
    <link href="~/Content/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/assets/css/form-elements.css" rel="stylesheet" />
    <link href="~/Content/assets/css/style.css" rel="stylesheet" />
</head>
<body>

    <!-- Top content -->
    <div class="top-content">

        <div class="inner-bg">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3 form-box">
                        <div class="form-top">
                            <div class="form-top-left">
                                <p>Enter your username and password to log on:</p>
                                <h4 style="color:red; text-align:center">@ViewBag.Thongbao</h4>
                            </div>
                            <div class="form-top-right">
                                <i class="fa fa-key"></i>
                            </div>
                        </div>
                        <div class="form-bottom">
                            @using (Html.BeginForm())
                            {
                                @Html.ValidationSummary(true)
                                <div class="form-group">
                                    <label class="sr-only" for="form-username">Username</label>
                                    <input type="text" name="username" placeholder="Username..." class="form-username form-control" id="form-username">
                                    @ViewData["Loi1"]
                                </div>
                                <div class="form-group">
                                    <label class="sr-only" for="form-password">Password</label>
                                    <input type="password" name="password" placeholder="Password..." class="form-password form-control" id="form-password">
                                    @ViewData["Loi2"]
                                </div>
                                <label><input type="checkbox" tabindex="3" />Save password</label>
                                <label><a href="@Url.Action("signin","Man")">Sign in now</a></label>
                                <button type="submit" class="btn">Sign in!</button>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <script src="~/Content/assets/js/jquery-1.11.1.min.js"></script>
    <link href="~/Content/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Content/assets/js/jquery.backstretch.min.js"></script>
    <script src="~/Content/assets/js/scripts.js"></script>
</body>
</html>